/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.tast_it2;


import static id.tast_it2.Stuff.*;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;


import javax.swing.JOptionPane;

/**
 *
 * @author Mohammad
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public LoginFrame() {
        initComponents();
         setSize(1220,800);
         setLocationRelativeTo(null);
         setResizable(false);
        Password_RecovoryPan.setVisible(false);
        CreateAccountPan.setVisible(false);
        LoginScreen.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginScreen = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        Login_TF_Password = new javax.swing.JPasswordField();
        Login_TF_UserName = new javax.swing.JTextField();
        button2 = new java.awt.Button();
        label1 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        jLabel144 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        Password_RecovoryPan = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        PW_Rec_User = new javax.swing.JTextField();
        PW_Rec_Old = new javax.swing.JTextField();
        PW_Rec_NEW = new javax.swing.JPasswordField();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel149 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CreateAccountPan = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jLabel145 = new javax.swing.JLabel();
        CreateAcc_TF_UserName = new javax.swing.JTextField();
        CreateAcc_TF_ADD1 = new javax.swing.JTextField();
        CreatAcc_TF_Password = new javax.swing.JPasswordField();
        CreateAcc_TF_Phone = new javax.swing.JTextField();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        CreateAcc_TF_ADD3 = new javax.swing.JTextField();
        label19 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginScreen.setMaximumSize(new java.awt.Dimension(1220, 800));
        LoginScreen.setMinimumSize(new java.awt.Dimension(1220, 800));
        LoginScreen.setOpaque(false);
        LoginScreen.setLayout(null);

        jPanel42.setForeground(new java.awt.Color(51, 51, 55));

        jPanel43.setBackground(new java.awt.Color(255, 255, 255));
        jPanel43.setMaximumSize(new java.awt.Dimension(516, 304));

        Login_TF_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_TF_PasswordActionPerformed(evt);
            }
        });

        Login_TF_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_TF_UserNameActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(255, 0, 0));
        button2.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        button2.setLabel("Login");
        button2.setName("Login"); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(204, 0, 0));
        label1.setText("Log In");

        label7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label7.setEnabled(false);
        label7.setFont(new java.awt.Font("Gabriola", 1, 12)); // NOI18N
        label7.setText("Username");

        label8.setEnabled(false);
        label8.setFont(new java.awt.Font("Gabriola", 1, 12)); // NOI18N
        label8.setText("Password");

        label9.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        label9.setText("Change Password ?");
        label9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label9MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label9MousePressed(evt);
            }
        });

        jLabel144.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel144.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel144.setText("Create Account");
        jLabel144.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel144MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel43Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login_TF_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login_TF_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel43Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel144, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66))
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Login_TF_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Login_TF_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel43Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel144, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LoginScreen.add(jPanel42);
        jPanel42.setBounds(370, 280, 470, 320);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginBackGround.png"))); // NOI18N
        LoginScreen.add(jLabel1);
        jLabel1.setBounds(0, 0, 1220, 800);

        Password_RecovoryPan.setMaximumSize(new java.awt.Dimension(1220, 800));
        Password_RecovoryPan.setMinimumSize(new java.awt.Dimension(1220, 800));
        Password_RecovoryPan.setOpaque(false);

        jPanel46.setBackground(new java.awt.Color(255, 255, 255));

        PW_Rec_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PW_Rec_UserActionPerformed(evt);
            }
        });

        PW_Rec_NEW.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        PW_Rec_NEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PW_Rec_NEWActionPerformed(evt);
            }
        });

        jLabel146.setForeground(new java.awt.Color(153, 153, 153));
        jLabel146.setText("Username");

        jLabel147.setForeground(new java.awt.Color(153, 153, 153));
        jLabel147.setText("Old Password");

        jLabel148.setForeground(new java.awt.Color(153, 153, 153));
        jLabel148.setText("New password");

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setLabel("Change Password");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel149.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel149.setForeground(new java.awt.Color(255, 0, 0));
        jLabel149.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel149.setText("Password Recovorey");

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel148)
                        .addComponent(jLabel147)
                        .addComponent(jLabel146)
                        .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PW_Rec_NEW, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PW_Rec_Old, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PW_Rec_User, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel46Layout.createSequentialGroup()
                        .addComponent(jLabel149, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel149)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel146)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PW_Rec_User, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel147)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PW_Rec_Old, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel148)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PW_Rec_NEW, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(32, 32, 32)
                .addComponent(jButton4))
        );

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addComponent(jPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginBackGround.png"))); // NOI18N

        javax.swing.GroupLayout Password_RecovoryPanLayout = new javax.swing.GroupLayout(Password_RecovoryPan);
        Password_RecovoryPan.setLayout(Password_RecovoryPanLayout);
        Password_RecovoryPanLayout.setHorizontalGroup(
            Password_RecovoryPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Password_RecovoryPanLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2)
        );
        Password_RecovoryPanLayout.setVerticalGroup(
            Password_RecovoryPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Password_RecovoryPanLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        CreateAccountPan.setMaximumSize(new java.awt.Dimension(1220, 800));
        CreateAccountPan.setMinimumSize(new java.awt.Dimension(1220, 800));

        jPanel44.setBackground(new java.awt.Color(255, 255, 255));

        jLabel145.setBackground(new java.awt.Color(255, 0, 0));
        jLabel145.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel145.setForeground(new java.awt.Color(255, 0, 0));
        jLabel145.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel145.setText("Create Account");

        CreateAcc_TF_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAcc_TF_UserNameActionPerformed(evt);
            }
        });

        label11.setEnabled(false);
        label11.setFont(new java.awt.Font("Gabriola", 1, 12)); // NOI18N
        label11.setText("Password");

        label12.setEnabled(false);
        label12.setFont(new java.awt.Font("Gabriola", 1, 12)); // NOI18N
        label12.setText("Username");

        label13.setEnabled(false);
        label13.setFont(new java.awt.Font("Gabriola", 1, 12)); // NOI18N
        label13.setText("Address1");

        label14.setEnabled(false);
        label14.setFont(new java.awt.Font("Gabriola", 1, 12)); // NOI18N
        label14.setText("Address2 (Optional)");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        label19.setEnabled(false);
        label19.setFont(new java.awt.Font("Gabriola", 1, 12)); // NOI18N
        label19.setText("Phone Number");

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel44Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton2)
                .addGap(88, 88, 88)
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel44Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel145, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateAcc_TF_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreatAcc_TF_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateAcc_TF_ADD1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateAcc_TF_ADD3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateAcc_TF_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(158, 158, 158))
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel145)
                .addGap(20, 20, 20)
                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(CreateAcc_TF_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(CreatAcc_TF_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(CreateAcc_TF_ADD1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(CreateAcc_TF_ADD3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(CreateAcc_TF_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginBackGround.png"))); // NOI18N

        javax.swing.GroupLayout CreateAccountPanLayout = new javax.swing.GroupLayout(CreateAccountPan);
        CreateAccountPan.setLayout(CreateAccountPanLayout);
        CreateAccountPanLayout.setHorizontalGroup(
            CreateAccountPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateAccountPanLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CreateAccountPanLayout.setVerticalGroup(
            CreateAccountPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateAccountPanLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2463, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LoginScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(Password_RecovoryPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1218, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CreateAccountPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LoginScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Password_RecovoryPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(CreateAccountPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_TF_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_TF_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_TF_PasswordActionPerformed

    private void Login_TF_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_TF_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_TF_UserNameActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed

        try {

            boolean F=false;

            String url="jdbc:oracle:thin:@localhost:1521:xe";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            Connection con=DriverManager.getConnection(url, "tast_it","654321");
            Statement stmt=con.createStatement();
            ResultSet set=stmt.executeQuery("Select * from CUSTOMER");

            while(set.next())
            {
                String UserName=set.getString(1);
                String Password=set.getString(2);
                String Phone=set.getString(3);

                if(UserName.equals(Login_TF_UserName.getText()) && Password.equals(Login_TF_Password.getText()))
                {
                    
                    F=true;
                    CurrentUser=Login_TF_UserName.getText();
                    CurrentUserPassword= Login_TF_Password.getText();
                    CurrentPhoneNumber=Phone;
                    Maintest frame=new Maintest();
                    frame.show();
                    dispose();

                }

            }
            if(F)
            {

                set=stmt.executeQuery("Select ADRESS1,ADRESS2 from ADDRESS where USERNAME_ID='"+CurrentUser+"'");
                set.next();

                String ADD1=set.getString(1);
                String ADD2=set.getString(2);
                CurrentAddress1=ADD1;
                CurrentAddress2=ADD2;
            }
            if(!F)
            {
                JOptionPane.showMessageDialog(null, "Wrong Login Credentials");
            }
            con.close();

        } catch (Exception ex) {
            Logger.getLogger(Maintest.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_button2ActionPerformed

    private void label9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label9MouseClicked

    }//GEN-LAST:event_label9MouseClicked

    private void label9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label9MousePressed
        LoginScreen.setVisible(false);
        Password_RecovoryPan.setVisible(true);
    }//GEN-LAST:event_label9MousePressed

    private void jLabel144MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel144MousePressed
        LoginScreen.setVisible(false);
        CreateAccountPan.setVisible(true);
    }//GEN-LAST:event_jLabel144MousePressed

    private void PW_Rec_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PW_Rec_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PW_Rec_UserActionPerformed

    private void PW_Rec_NEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PW_Rec_NEWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PW_Rec_NEWActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {

            boolean F=false;

            String url="jdbc:oracle:thin:@localhost:1521:xe";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            Connection con=DriverManager.getConnection(url, "tast_it","654321");
            Statement stmt=con.createStatement();
            ResultSet set=stmt.executeQuery("Select * from CUSTOMER");

            while(set.next())
            {
                String UserName=set.getString(1);
                String Password=set.getString(2);

                if(UserName.equals(PW_Rec_User.getText()) && Password.equals(PW_Rec_Old.getText()))
                {
                    stmt.executeUpdate("UPDATE CUSTOMER SET PASSWORD = "+"'"+PW_Rec_NEW.getText()+"'"+"WHERE PASSWORD = "+"'"+PW_Rec_Old.getText()+"'");
                      JOptionPane.showMessageDialog(rootPane, "Password Changed");
                    F=true;
                }

            }
            if(!F)
            {
                JOptionPane.showMessageDialog(null, "Wrong Credentials");
            }
            con.commit();
            con.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString() );

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        LoginScreen.setVisible(true);
        Password_RecovoryPan.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CreateAcc_TF_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAcc_TF_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateAcc_TF_UserNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            String url="jdbc:oracle:thin:@localhost:1521:xe";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            Connection con=DriverManager.getConnection(url, "tast_it","654321");
            Statement stmt=con.createStatement();
            String stmtStat="insert into CUSTOMER values("+"'"+this.CreateAcc_TF_UserName.getText()+"','"+this.CreatAcc_TF_Password.getText()+"','"+CreateAcc_TF_Phone.getText()+"')";
            stmt.executeUpdate(stmtStat);
            String stmtStat2="insert into ADDRESS values("+"'"+this.CreateAcc_TF_UserName.getText()+"','"+this.CreateAcc_TF_ADD1.getText()+"','"+this.CreateAcc_TF_ADD3.getText()+"')";
            stmt.executeUpdate(stmtStat2);
            JOptionPane.showMessageDialog(rootPane, "Account Created!");
            con.commit();
            con.close();
        }
        catch (Exception ex)
        {

            JOptionPane.showMessageDialog(null, ex.toString());

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginScreen.setVisible(true);
        CreateAccountPan.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CreatAcc_TF_Password;
    private javax.swing.JTextField CreateAcc_TF_ADD1;
    private javax.swing.JTextField CreateAcc_TF_ADD3;
    private javax.swing.JTextField CreateAcc_TF_Phone;
    private javax.swing.JTextField CreateAcc_TF_UserName;
    private javax.swing.JPanel CreateAccountPan;
    private javax.swing.JPanel LoginScreen;
    private javax.swing.JPasswordField Login_TF_Password;
    private javax.swing.JTextField Login_TF_UserName;
    private javax.swing.JPasswordField PW_Rec_NEW;
    private javax.swing.JTextField PW_Rec_Old;
    private javax.swing.JTextField PW_Rec_User;
    private javax.swing.JPanel Password_RecovoryPan;
    private java.awt.Button button2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JSeparator jSeparator7;
    private java.awt.Label label1;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label19;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
